config/routes.rb
FlatRent::Application.routes.draw do
  resources :rank_of_users

  resources :searchoffers

  resources :offers

  devise_for :users
  resources :events
  root :to => redirect('/events')

  match 'users/:id' => 'users#show', via: :get
  get 'users/:id' => 'users#show'

end

app/models/event.rb
class Event < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  mount_uploader :offerPicture, PictureUploader
  belongs_to :user
end

app/models/rank_of_user.rb
class RankOfUser < ActiveRecord::Base
end

app/models/searchoffer.rb
class Searchoffer < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :picture, :start_date, :start_time, :end_time, :likes, :user_id, :tag_id, :location_id, :comment_id)
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offer }
      else
        format.html { render action: 'new' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:offerTitle, :offerCos, :offerPicture, :offerStart_date, :user_id, :offerEnd_date, :offerType_building_id, :offerArea, :offerRooms, :offerLocalization, :offerMail_contact, :offerPhone_contact, :offerDescription)
    end
end

app/controllers/rank_of_users_controller.rb
class RankOfUsersController < ApplicationController
  before_action :set_rank_of_user, only: [:show, :edit, :update, :destroy]

  # GET /rank_of_users
  # GET /rank_of_users.json
  def index
    @rank_of_users = RankOfUser.all
  end

  # GET /rank_of_users/1
  # GET /rank_of_users/1.json
  def show
  end

  # GET /rank_of_users/new
  def new
    @rank_of_user = RankOfUser.new
  end

  # GET /rank_of_users/1/edit
  def edit
  end

  # POST /rank_of_users
  # POST /rank_of_users.json
  def create
    @rank_of_user = RankOfUser.new(rank_of_user_params)

    respond_to do |format|
      if @rank_of_user.save
        format.html { redirect_to @rank_of_user, notice: 'Rank of user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rank_of_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @rank_of_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rank_of_users/1
  # PATCH/PUT /rank_of_users/1.json
  def update
    respond_to do |format|
      if @rank_of_user.update(rank_of_user_params)
        format.html { redirect_to @rank_of_user, notice: 'Rank of user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rank_of_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rank_of_users/1
  # DELETE /rank_of_users/1.json
  def destroy
    @rank_of_user.destroy
    respond_to do |format|
      format.html { redirect_to rank_of_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rank_of_user
      @rank_of_user = RankOfUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rank_of_user_params
      params[:rank_of_user]
    end
end

app/controllers/users_controller.rb
class Usersontroller < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/rank_of_users_helper.rb
module RankOfUsersHelper
end

app/helpers/searchoffers_helper.rb
module SearchoffersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>


  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Start date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Likes</th>
      <th>User</th>
      <th>Tag</th>
      <th>Location</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= image_tag(event.picture_url, :width => 600) if event.picture.present? %></td>
        <td><%= event.start_date %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.likes %></td>
        <td><%= event.user_id %></td>
        <td><%= event.tag_id %></td>
        <td><%= event.location_id %></td>
        <td><%= event.comment_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@event.picture_url, :width => 600) if @event.picture.present? %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @event.likes %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @event.tag_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @event.comment_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlatRent</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag "default", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The flat_rent app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/events">Events</a></li>
        <li class="active"><a href="/offers">Housing offers</a></li>
        <li class="active"><a href="/rank_of_users">Ranking of users</a></li>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>

            <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </div>
  </div>
</nav>



<footer>
  <div class="container">
    flat_rent 2014
  </div>
</footer>

<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :"Offer title"%><br>
  <%= f.text_area :offerTitle, :cols => "40", :rows => "2" %>
  </div>
    <div class="field">
      <%= f.label :Cost%><br>
      <%= f.number_field :offerCos %> zł
    </div>
    <div class="field">
      <%= f.label :Picture%><br>
      <%= f.file_field  :offerPicture %>
    </div>
    <div class="field">
      <%= f.label :"Start date"%><br>
      <%= f.date_select :offerStart_date %><br>
      <%= f.label :"End date"%><br>
      <%= f.date_select :offerEnd_date %>
    </div>
    <div class="field">
      <%= f.label :"Type of building"%><br>
      <%= f.text_area :offerType_building_id %>
    </div>
    <div class="field">
      <%= f.label :"Measurement"%><br>
      <%= f.number_field :offerArea %> m<sup>2</sup>
    </div>
    <div class="field">
      <%= f.label :"Number of rooms"%><br>
      <%= f.number_field :offerRooms %>
    </div>
    <div class="field">
      <%= f.label :"Adress"%><br>
      <%= f.text_area :offerLocalization, :cols => "30", :rows => "5" %>
    </div>
    <div class="field">
      <%= f.label :"Email"%><br>
      <%= f.text_field :offerMail_contact %>
    </div>
    <div class="field">
      <%= f.label :"Phone"%><br>
      <%= f.text_field :offerPhone_contact %>
    </div>
    <div class="field">
      <%= f.label :"Description"%><br>
      <%= f.text_area :offerDescription, :cols => "40", :rows => "5" %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= image_tag(offer.offerPicture_url, :width => 300) if offer.offerPicture.present? %></td>
        <td><%= offer.offerTitle %></td>
        <td><%= offer.offerStart_date %></td>
        <td><%= offer.offerEnd_date %></td>
        <td><%= offer.offerLocalization %></td>
        <td><%= offer.offerCos %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.offerTitle %>
</p>
<p>
  <strong>Cost:</strong>
  <%= @offer.offerCos %>
</p>
<p>
  <strong>Picture:</strong>
  <%= image_tag(@offer.offerPicture_url, :width => 300) if @offer.offerPicture.present? %>
</p>
<p>
  <strong>Start date:</strong>
  <%= @offer.offerStart_date %>
</p>
<p>
  <strong>End date:</strong>
  <%= @offer.offerEnd_date %>
</p>
<p>
  <strong>Type of building:</strong>
  <%= @offer.offerType_building_id %>
</p>
<p>
  <strong>Measurement:</strong>
  <%= @offer.offerArea %>
</p>
<p>
  <strong>Number of rooms:</strong>
  <%= @offer.offerRooms %>
</p>
<h3>Adress</h3>
<p>
  <strong>Adress:</strong>
  <%= @offer.offerLocalization %>
</p>
<h3>Contact</h3>
<p>
  <strong>Email:</strong>
  <%= @offer.offerMail_contact %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @offer.offerPhone_contact %>
</p>
<p>
  <strong>Description:</strong>
  <%= @offer.offerDescription %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

app/views/rank_of_users/_form.html.erb
<%= form_for(@rank_of_user) do |f| %>
  <% if @rank_of_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank_of_user.errors.count, "error") %> prohibited this rank_of_user from being saved:</h2>

      <ul>
      <% @rank_of_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rank_of_users/edit.html.erb
<h1>Editing rank_of_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank_of_user %> |
<%= link_to 'Back', rank_of_users_path %>

app/views/rank_of_users/index.html.erb
<h1>Listing rank_of_users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rank_of_users.each do |rank_of_user| %>
      <tr>
        <td><%= link_to 'Show', rank_of_user %></td>
        <td><%= link_to 'Edit', edit_rank_of_user_path(rank_of_user) %></td>
        <td><%= link_to 'Destroy', rank_of_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rank of user', new_rank_of_user_path %>

app/views/rank_of_users/new.html.erb
<h1>New rank_of_user</h1>

<%= render 'form' %>

<%= link_to 'Back', rank_of_users_path %>

app/views/rank_of_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rank_of_user_path(@rank_of_user) %> |
<%= link_to 'Back', rank_of_users_path %>